// AUTO-GENERATED by the Docker build (see Dockerfile) — DO NOT EDIT BY HAND.
// Holds the git commit this image was built from. Committed as a `null`
// placeholder; the build overwrites it with the real SHA (OSS reads it from git,
// the private wrapper writes the vendored submodule commit here). Stays null in
// local dev / non-git builds, in which case the version footer is hidden.

export const buildSha: string | null = null;
